Codezync.POS.System/Codezync.Pos.Web/Controllers/CustomerController.cs
using Codezync.Pos.Data.Service;
using Codezync.Pos.Data.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace Codezync.Pos.Web.Controllers
{
    public class CustomerController : BaseController
    {
        private CustomerService customerService;

        private string BASE_URL = ConfigurationManager.AppSettings["BaseUrl"];

        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            customerService = new CustomerService(CZDBContext);

        }
        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult ViewCustomer(int customerId = 0)
        {
            var _Customer = customerService.GetCustomerById(customerId);
            if (_Customer != null)
                return PartialView("_ViewCustomer", _Customer);
            return PartialView("_ViewCustomer", new CustomerViewModel());

        }

        public PartialViewResult CustomerList(string searchKey, int page = 1)
        {
            var _CustomerList = customerService.GetCustomersList(searchKey, page);
            return PartialView("_CustomerList", _CustomerList);
        }

        [HttpGet]
        //CreateCustomer
        public PartialViewResult CreateCustomer()
        {
            
            var _Customer = new CustomerViewModel();
           
            return PartialView("_CreateCustomer", _Customer);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateCustomer(CustomerViewModel model, HttpPostedFileBase file)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (file != null)
                    {
                        var url = $"{BASE_URL}/Content/customerImages/{file.FileName}";
                        file.SaveAs(HttpContext.Server.MapPath("~/Content/customerImages/")
                                                              + file.FileName);
                        model.CustomerImgeUrl = url;
                    }
                    
                    customerService.addCustomer(model);
                    return Redirect("Index");

                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex);
            }
         return View();

        }

        public PartialViewResult EditCustomer(int customerId = 0)
        {

            var _Customer = new CustomerViewModel();
            
            if (customerId != 0) {
                _Customer = customerService.GetCustomerById(customerId);
            }
            return PartialView("_EditCustomer", _Customer);

        }
        public async Task<ActionResult> SetCustomer(int customerId = 0)
        {
            if (Session["CART_ID"] != null)
            {
                customerService.setCustomer(customerId, Session["CART_ID"].ToString());
            }
            
            return RedirectToAction("Index","POS");

        }
        public async Task<ActionResult> DeleteCustomer(int customerId = 0)
        {
            
            customerService.deleteCustomer(customerId);
            return Redirect("Index");

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditCustomer(CustomerViewModel model, HttpPostedFileBase file)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (file != null)
                    {
                        var url = $"{BASE_URL}/Content/customerImages/{file.FileName}";
                        file.SaveAs(HttpContext.Server.MapPath("~/Content/customerImages/")
                                                              + file.FileName);
                        model.CustomerImgeUrl = url;
                    }

                    customerService.editCustomer(model);
                    return Redirect("Index");

                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex);
            }
            return View();

        }


    }
}

Codezync.POS.System/Codezync.Pos.Web/Controllers/PaymentController.cs
using Codezync.Pos.Data.Service;
using Codezync.Pos.Data.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Microsoft.AspNet.Identity;

namespace Codezync.Pos.Web.Controllers
{
    public class PaymentController : BaseController
    {
        private OrderService orderService;
        private CartService cartService;
        private PaymentService paymentService;
        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            orderService = new OrderService(CZDBContext);
            cartService = new CartService(CZDBContext);
            paymentService = new PaymentService(CZDBContext);
        }
        // GET: Payment
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// to identify previously selected payment type
        /// </summary>
        /// <returns></returns>
        public JsonResult GetCurrentPaymentType()
        {
            if (Session["CART_ID"] != null)
            {
                return Json(cartService.GetCurrentPaymentType(Session["CART_ID"].ToString()), JsonRequestBehavior.AllowGet);
            }

            var getPaymentType = cartService.GetCurrentPaymentType();
            return Json(getPaymentType, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// get curret cart data to show when landing to payment control
        /// </summary>
        /// <returns></returns>
        public JsonResult GetCurrentCartData()
        {
            if (Session["CART_ID"] != null)
            {
                var summery = cartService.GetCartSummery(Session["CART_ID"].ToString());
                return Json(new { total = summery.TotalAmount, customerId = summery.CustomerId }, JsonRequestBehavior.AllowGet);
            }

            var _summery = cartService.GetCartSummery();
            return Json(new { total = _summery.TotalAmount, customerId = _summery.CustomerId }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// save cash payment when selected payment type as cash
        /// </summary>
        /// <param name="paidAmount"></param>
        /// <param name="total"></param>
        /// <param name="customerId"></param>
        /// <param name="discountRate"></param>
        /// <returns></returns>
        public JsonResult SaveAsCashPayment(double paidAmount, double total, int customerId, double discountRate)
        {
            var paymentId = paymentService.AddCashPayment(paidAmount, total, customerId);
            if (paymentId != 0)
            {
                cartService.AddCashPayment(paymentId, discountRate);
                return Json(true, JsonRequestBehavior.AllowGet);
            }

            return Json(false, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// save card payments when card selected as payment type
        /// </summary>
        /// <param name="cardReference"></param>
        /// <param name="total"></param>
        /// <param name="customerId"></param>
        /// <param name="discountRate"></param>
        /// <returns></returns>
        public JsonResult SaveAsCardPayment(string cardReference, double total, int customerId, double discountRate)
        {
            var paymentId = paymentService.AddCardPayment(cardReference, total, customerId);
            if (paymentId != 0)
            {
                cartService.AddCardPayment(paymentId, discountRate);
                return Json(true, JsonRequestBehavior.AllowGet);
            }

            return Json(false, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Here the order will be permanently saved in the dbb and will show the
        /// invoice and clear the session for current order.
        /// </summary>
        /// <returns></returns>
        public ActionResult Invoice()
        {
            if (Session["CART_ID"] != null)
            {
                var CashierId = User.Identity.GetUserId();
                var orderId = orderService.SaveAnOrder(CashierId, Session["CART_ID"].ToString());
                var summery = orderService.GetInvoiceSummery(orderId);

                cartService.ClearCart(Session["CART_ID"].ToString());
                Session["CART_ID"] = null;
                

                return View(summery);
            }
            return RedirectToAction("Index","POS");
        }


    }
}

Codezync.POS.System/Codezync.Pos.Web/Views/Payment/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*Header*@
<div class="row">
    <div class="col-md-1">
    </div>
    <div class="col-md-10">
        <div class="breadcrumb bc-colored  bg-info">
            <div class="row">
                <div class="col-md-5">
                    <a class="btn btn-primary" href="@Url.Action("Index","POS")">
                        <span class="btn-label"><i class="fa fa-arrow-left"></i></span>
                        Back
                    </a>
                </div>
                <div class="col-md-2">
                    <h2 style="color:#ffffff;">Payments</h2>
                </div>
                <div class="col-md-5">

                </div>
            </div>
            
        </div>
    </div>
    <div class="col-md-1">
    </div>

</div>
<br />
@*payment selection*@
<div class="row">

    <div class="col-md-1">

    </div>
    <div class="col-md-10">
        <div class="card">
            <div class="card-block">
                <div class="row">
                    <div class="col-md-6">
                        <button onclick="getCurrentPaymentType()" type="button" class="btn btn-block btn-lg btn-success">CASH PAYMENTS</button>
                    </div>
                    <div class="col-md-6">
                        <button onclick="showCardPayments()" type="button" class="btn btn-block btn-lg btn-success">CARD PAYMENTS</button>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="col-md-1">

    </div>
</div>

@*payment sumery list*@
<div class="row">

    <div class="col-md-1">
        <span id="customerId"></span>
    </div>
    <div class="col-md-10">
        <div class="card">
            <div class="card-block">
                <div class="row">
                    @*@Html.Action("CustomerList", "Customer")*@
                    <div id="cashPayDiv" class="table-responsive">
                        <table class="table color-table muted-table">
                           
                            <thead>
                                <tr>
                                    <td>Due</td>
                                    <td>Tendered</td>
                                    <td>DiscountRate</td>
                                    <td>Change</td>
                                    <td>Total With Discounts</td>
                                    <td>Method</td>
                                    <td>Action</td>
                                </tr>
                                <tr>
                                    <th><label><strong id="due">0.00</strong></label></th>
                                    <th><input id="payed" type="text" placeholder="00.00" class="form-control"/></th>
                                    <th><input id="rate" type="number" placeholder="00.00" class="form-control" /></th>
                                    <th><label><strong id="change">0.0</strong></label></th>
                                    <th><label><strong id="net_total">0.00</strong></label></th>
                                    <th><label><strong>CASH</strong></label></th>
                                    <th><button onclick="saveAsCashPayment()"><i class="fa fa-save (alias)"></i></button></th>
                                </tr>
                            </thead>
                        </table>                      

                    </div>

                    <div id="cardPayDiv" class="table-responsive">
                        <table class="table color-table muted-table">

                            <thead>
                                <tr>
                                    <td>Due</td>
                                    <td>Card Reference#</td>
                                    <td>DiscountRate</td>
                                    <td>Total With Discounts</td>
                                    <td>Method</td>
                                    <td>Action</td>
                                </tr>
                                <tr>
                                    <th><label><strong id="cardDue">0.00</strong></label></th>
                                    <th><input id="cardRef" type="text" placeholder="00000" class="form-control" /></th>
                                    <th><input id="cardRate" type="number" placeholder="00.00" class="form-control" /></th>
                                    <th><label><strong id="net_total_card">0.00</strong></label></th>                                    
                                    <th><label><strong>CARD</strong></label></th>
                                    <th><button onclick="saveAsCardPayment()"><i class="fa fa-save (alias)"></i></button></th>
                                </tr>
                            </thead>
                        </table>

                    </div>


                </div>
            </div>
        </div>
    </div>

    <div class="col-md-1">

    </div>
</div>

@*invoice button*@
<div class="row">

    <div class="col-md-1">
    </div>
    <div class="col-md-10">
        <div class="row">
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
                <a class="btn btn-lg btn-danger" href="@Url.Action("Invoice","Payment")">
                    <span class="btn-label"><i class="fa fa-file-text"></i></span>
                    Invoice
                </a>
            </div>
            <div class="col-md-4">
            </div>
        </div>
    </div>

    <div class="col-md-1">

    </div>
</div>

<script>

    init()

    function showCashPayments() {
        $('#cashPayDiv').show();
        $('#cardPayDiv').hide();
    }

    function showCardPayments() {
        $('#cashPayDiv').hide();
        $('#cardPayDiv').show();
    }
    function getCurrentPaymentType() {
       

        $.getJSON('/Payment/GetCurrentPaymentType', function (data) {
            if (data == 1) {
                showCardPayments()
            } else {
                showCashPayments()
            }
            
        });
    }
    function init() {

        getCurrentPaymentType();


        $('#customerId').hide();

        $.getJSON('/Payment/GetCurrentCartData', function (data) {
            $('#due').text(data.total);
            $('#cardDue').text(data.total);
            $('#customerId').text(data.customerId); 
        });
    }

    function saveAsCardPayment() {

       
        var due = $('#due').text();
        var value = $("#cardRef").val();
        var customerId = $('#customerId').text();
        var discountRate = $('#cardRate').val(); 

        if (value == '') {
            alert('Please add card reference number!');
        } else {
            $.ajax({
                type: 'POST',
                url: '/Payment/SaveAsCardPayment',
                data: { 'cardReference': value, 'total': due, 'customerId': customerId ,'discountRate': discountRate },
                dataType: 'json',
                success: function (data) {
                    if (data) {
                        alert('Card Payment Saved!');
                    }
                }
            });
        }
        
    }
    function saveAsCashPayment() {
        var due = $('#due').text();
        var value = $("#payed").val();
        var customerId = $('#customerId').text(); 
        var discountRate = $('#rate').val(); 

        if (value == '') {
            alert('Please add cash amount paid!');
        } else {
            $.ajax({
                type: 'POST',
                url: '/Payment/SaveAsCashPayment',
                data: { 'paidAmount': value, 'total': due, 'customerId': customerId, 'discountRate': discountRate },
                dataType: 'json',
                success: function (data) {
                    if (data) {
                        alert('Cash Payment Saved!');
                    }
                }
            }); 
        }

       
       
    }

   

    $('#payed').keyup(function () {
        
        var due = $('#due').text();
        var value = $("#payed").val();
        var discount = $("#rate").val();
        var totalwithDiscounts = due - ((discount/100) * due);
        
        var balance = value - totalwithDiscounts;

        //balance
        $('#change').text(balance);
        //total with Discounts
        $('#net_total').text(totalwithDiscounts);

        
        
    });

    $('#rate').keyup(function () {

        var due = $('#due').text();
        var value = $("#payed").val();
        var discount = $("#rate").val();
        var totalwithDiscounts = due - ((discount / 100) * due);

        var balance = value - totalwithDiscounts;

        //balance
        $('#change').text(balance);
        //total with Discounts
        $('#net_total').text(totalwithDiscounts);
        

    });
    $('#cardRate').keyup(function () {

        //for car payemts
        var cardDue = $('#cardDue').text();
        var cardRate = $('#cardRate').text();
        var totalwithDiscounts_card = cardDue - ((discount/100) * cardDue);
        //total with Discounts
        $('#net_total_card').text(totalwithDiscounts_card);


    });

</script>

Codezync.POS.System/Codezync.Pos.Web/Views/Payment/Invoice.cshtml
@model Codezync.Pos.Data.ViewModels.InvoiceSumeryViewModel
@{
    ViewBag.Title = "Invoice";
}

<div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
        <div class="card card-block printableArea">
            <h3><b>INVOICE</b> <span class="pull-right">@Model.OrderId</span></h3>
            <hr>
            <div class="row">
                <div class="col-md-12">
                    <div class="pull-left">
                        <address>
                            <h3> &nbsp;<b class="text-danger">@Model.Customer.Name</b></h3>
                            <p class="text-muted m-l-5">
                                @Model.Customer.Address
                            </p>
                            <p class="text-muted m-l-5">
                                @Model.Customer.Email
                            </p>
                            <p class="text-muted m-l-5">
                                @Model.Customer.Phone
                            </p>
                        </address>
                    </div>
                    <div class="pull-right text-right">
                        <address>                           
                            <p class="m-t-30"><b>Invoice Date :</b> <i class="fa fa-calendar"></i> @Model.Date</p>
                        </address>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="table-responsive m-t-40" style="clear: both;">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th class="text-center">#</th>
                                    <th>Description</th>
                                    <th class="text-right">Quantity</th>
                                    <th class="text-right">Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.OrderedItems)
                                {
                                    <tr>
                                        <td class="text-center">@item.Id</td>
                                        <td>@item.Product.Name</td>
                                        <td class="text-right"> @item.Quantity </td>
                                        <td class="text-right"> @item.Price </td>
                                    </tr>

                                }
                                
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="pull-right m-t-30 text-right">
                        <p>Sub - Total amount: $13,848</p>
                        <p>Discount Rate : 1.2% </p>
                        <p>Paid Amount :  </p>
                        <hr>
                        <h3><b>Total :</b> $13,986</h3>
                    </div>
                    <div class="clearfix"></div>
                    <hr>
                    
                </div>
            </div>
        </div>
        <div class="text-right">
            <a class="btn btn-danger" href="@Url.Action("Index","POS")"> Next Order </a>
            <button id="print" class="btn btn-default btn-outline" type="button"> <span><i class="fa fa-print"></i> Print</span> </button>
        </div>
    </div>
    <div class="col-md-2">

    </div>
</div>

<script src="~/js/jquery.PrintArea.js"></script>
<script>
    $(document).ready(function() {
        $("#print").click(function() {
            var mode = 'iframe'; //popup
            var close = mode == "popup";
            var options = {
                mode: mode,
                popClose: close
            };
            $("div.printableArea").printArea(options);
        });
    });
</script>